select * from tab;

-- table 생성
CREATE TABLE STUDENTS 
(
  STD_NUM NUMBER(2) NOT NULL 
, STD_NAME VARCHAR2(20) NOT NULL 
, STD_TEL VARCHAR2(20) 
, CONSTRAINT STUDENTS_PK PRIMARY KEY 
  (
    STD_NUM 
  )
  ENABLE 
);
COMMENT ON COLUMN STUDENTS.STD_NUM IS '학생번호';
COMMENT ON COLUMN STUDENTS.STD_NAME IS '학생이름';
COMMENT ON COLUMN STUDENTS.STD_TEL IS '학생전화번호';
-- table 삭제
DROP TABLE STUDENTS;
-- table 수정1
ALTER TABLE STUDENTS RENAME COLUMN STD_TEL TO STD_PHONE;
-- table 수정2
ALTER TABLE STUDENTS -- 컬럼 추가
ADD (M_ID NUMBER(2) );

ALTER TABLE STUDENTS -- 외래키 제약조건 추가
ADD CONSTRAINT STUDENTS_FK1 FOREIGN KEY
(
  M_ID 
)
REFERENCES MAJOR
(
  M_ID 
)
ON DELETE SET NULL ENABLE;


-- table 생성
CREATE TABLE MAJOR 
(
  M_ID NUMBER(2) NOT NULL 
, M_NAME VARCHAR2(20) NOT NULL 
, MGR_ID NUMBER(2) 
, CONSTRAINT MAJOR_PK PRIMARY KEY 
  (
    M_ID 
  )
  ENABLE 
);
COMMENT ON COLUMN MAJOR.M_ID IS '학부번호';
COMMENT ON COLUMN MAJOR.M_NAME IS '학부이름';
COMMENT ON COLUMN MAJOR.MGR_ID IS '과대표번호';
-- table 삭제
DROP TABLE MAJOR;
-- table 수정
ALTER TABLE MAJOR -- 외래키 제약 조건
ADD CONSTRAINT MAJOR_FK1 FOREIGN KEY
(
  MGR_ID 
)
REFERENCES STUDENTS
(
  STD_NUM 
)
ON DELETE SET NULL ENABLE;


-- table 생성
CREATE TABLE SPORTS 
(
  S_ID NUMBER(2) NOT NULL 
, S_NAME VARCHAR2(20) NOT NULL 
, MGR_ID NUMBER(2) 
, CONSTRAINT SPORTS_PK PRIMARY KEY 
  (
    S_ID 
  )
  ENABLE 
);
COMMENT ON COLUMN SPORTS.S_ID IS '스포츠번호';
COMMENT ON COLUMN SPORTS.S_NAME IS '스포츠명';
COMMENT ON COLUMN SPORTS.MGR_ID IS '주장번호';
-- table 삭제
DROP TABLE SPORTS;
-- table 수정
ALTER TABLE SPORTS
ADD CONSTRAINT SPORTS_FK1 FOREIGN KEY
(
  S_ID 
)
REFERENCES PLAYERS
(
  P_ID 
)
ENABLE;


-- table 생성
CREATE TABLE PLAYERS 
(
  P_ID NUMBER(2) PRIMARY KEY 
, P_NAME VARCHAR2(20) NOT NULL 
, S_ID NUMBER(2) 
, SALARY NUMBER 
);
COMMENT ON COLUMN PLAYERS.P_ID IS '선수번호';
COMMENT ON COLUMN PLAYERS.P_NAME IS '선수명';
COMMENT ON COLUMN PLAYERS.S_ID IS '스포츠번호';
COMMENT ON COLUMN PLAYERS.SALARY IS '급여';
-- table 삭제
DROP TABLE PLAYERS;
-- table 수정
ALTER TABLE PLAYERS
ADD CONSTRAINT PLAYERS_FK1 FOREIGN KEY
(
  S_ID 
)
REFERENCES SPORTS
(
  S_ID 
)
ON DELETE SET NULL ENABLE;

------------------------------------------------
INSERT INTO "TEST"."STUDENTS" (STD_NUM, STD_NAME, STD_PHONE) VALUES ('1', 'kim', '010');
INSERT INTO "TEST"."MAJOR" (M_ID, M_NAME, MGR_ID) VALUES ('90', 'it', '1');
UPDATE "TEST"."STUDENTS" SET M_ID = '90' WHERE ROWID = 'AAAE5cAABAAALCxAAA' AND ORA_ROWSCN = '389724';
