-- USER HR
CONN SYSTEM/hi123456;
ALTER USER HR IDENTIFIED BY hi123456 ACCOUNT UNLOCK;
CONN HR/hi123456;

-- USER TEST
CREATE USER "TEST" IDENTIFIED BY "hi123456";
-- ROLES
GRANT "CONNECT" TO "TEST" ;
GRANT "RESOURCE" TO "TEST" ;
-- SYSTEM PRIVILEGES
GRANT CREATE VIEW TO "TEST" ;

SELECT * FROM TAB;
